# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-21 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jupiter_auth', '0012_auto_20161230_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='number_of_times_0_5_days_late',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='number_of_times_5_29_days_late',
            field=models.IntegerField(default=0),
        ),
    ]
